dha-pod-config-metadata:
  title: Deployment Hardware Adapter (DHA) for fuel development pipeline - default version
  version: 0.0.3
  created: Feb 1 2016
  comment: Default Fuel8 version

# Adapter to use for this definition
adapter: zte

# Node list.
# Mandatory property is id, all other properties are adapter specific.

nodes:
- id: 1
  pxeMac: 74:4A:A4:00:CF:DC
  ipmiIp: 192.168.1.101
  ipmiUser: zteroot
  ipmiPass: superuser
- id: 2
  pxeMac: 74:4A:A4:00:CE:CE
  ipmiIp: 192.168.1.102
  ipmiUser: zteroot
  ipmiPass: superuser
- id: 3
  pxeMac: 74:4A:A4:00:CF:58
  ipmiIp: 192.168.1.103
  ipmiUser: zteroot
  ipmiPass: superuser
- id: 4
  pxeMac: 74:4A:A4:00:49:84
  ipmiIp: 192.168.1.104
  ipmiUser: zteroot
  ipmiPass: superuser
- id: 5
  pxeMac: 74:4A:A4:00:CE:C2
  ipmiIp: 192.168.1.105
  ipmiUser: zteroot
  ipmiPass: superuser

# Adding the Fuel node as node id 6 which may not be correct - please
# adjust as needed.
- id: 7
  libvirtName: fuel-opnfv-1
  libvirtTemplate: templates/hardware_environment/vms/fuel.xml
  isFuel: yes
  username: root
  password: r00tme

disks:
  fuel: 100G
