dea-pod-override-config-metadata:
  title: 'Deployment Environment Adapter POD override for Ericsson, POD1'
  version: '0.1'
  created: 'Fri Mar  4 2016'
  comment: 'None'
environment:
  name: FUEL-BM-POD1
interfaces_1:
  eno1:
  - fuelweb_admin
  ens1f0:
  - public
  - management
  - storage
  - private
transformations_1:
  transformations:
  - action: add-br
    name: br-fw-admin
  - action: add-br
    name: br-mgmt
  - action: add-br
    name: br-storage
  - action: add-br
    name: br-ex
  - action: add-br
    name: br-floating
    provider: ovs
  - action: add-patch
    bridges:
    - br-floating
    - br-ex
    mtu: 65000
    provider: ovs
  - action: add-br
    name: br-mesh
  - action: add-port
    bridge: br-fw-admin
    name: eno1
  - action: add-port
    bridge: br-mgmt
    name: ens1f0.901
  - action: add-port
    bridge: br-storage
    name: ens1f0.902
  - action: add-port
    bridge: br-ex
    name: ens1f0.752
  - action: add-port
    bridge: br-mesh
    name: ens1f0.103
fuel:
  ADMIN_NETWORK:
    dhcp_pool_end: 10.20.0.254
    dhcp_pool_start: 10.20.0.12
    ipaddress: 10.20.0.2
    netmask: 255.255.255.0
  DNS_DOMAIN: domain.tld
  DNS_SEARCH: domain.tld
  DNS_UPSTREAM: 10.118.32.193
  FUEL_ACCESS:
    password: admin
    user: admin
  HOSTNAME: fuel
  NTP1: 10.118.32.193
  NTP2: ''
  NTP3: ''
network:
  networking_parameters:
    base_mac: fa:16:3e:00:00:00
    configuration_template: null
    dns_nameservers:
    - 8.8.4.4
    - 8.8.8.8
    floating_name: admin_floating_net
    floating_ranges:
    - - 10.118.36.176
      - 10.118.36.185
    gre_id_range:
    - 2
    - 65535
    internal_cidr: 192.168.111.0/24
    internal_gateway: 192.168.111.1
    internal_name: admin_internal_net
    net_l23_provider: ovs
    segmentation_type: tun
    vlan_range:
    - 1000
    - 1030
  networks:
  - cidr: 10.118.36.0/24
    gateway: 10.118.36.1
    ip_ranges:
    - - 10.118.36.165
      - 10.118.36.175
    meta:
      cidr: 172.16.0.0/24
      configurable: true
      floating_range_var: floating_ranges
      ip_range:
      - 172.16.0.2
      - 172.16.0.126
      map_priority: 1
      name: public
      notation: ip_ranges
      render_addr_mask: public
      render_type: null
      use_gateway: true
      vips:
      - haproxy
      - vrouter
      vlan_start: null
    name: public
    vlan_start: 752
  - cidr: 192.168.20.0/24
    gateway: null
    ip_ranges:
    - - 192.168.20.12
      - 192.168.20.254
    meta:
      cidr: 192.168.1.0/24
      configurable: true
      map_priority: 2
      name: storage
      notation: ip_ranges
      render_addr_mask: storage
      render_type: cidr
      use_gateway: false
      vlan_start: 102
    name: storage
    vlan_start: 902
  - cidr: 192.168.10.0/24
    gateway: null
    ip_ranges:
    - - 192.168.10.1
      - 192.168.10.254
    meta:
      cidr: 192.168.0.0/24
      configurable: true
      map_priority: 2
      name: management
      notation: cidr
      render_addr_mask: internal
      render_type: cidr
      use_gateway: false
      vips:
      - haproxy
      - vrouter
      vlan_start: 101
    name: management
    vlan_start: 901
  - cidr: 192.168.2.0/24
    gateway: null
    ip_ranges:
    - - 192.168.2.1
      - 192.168.2.254
    meta:
      cidr: 192.168.2.0/24
      configurable: true
      map_priority: 2
      name: private
      notation: cidr
      render_addr_mask: null
      render_type: cidr
      seg_type: tun
      use_gateway: false
      vlan_start: 103
    name: private
    vlan_start: 103
  - cidr: 10.20.0.0/24
    gateway: 10.20.0.2
    ip_ranges:
    - - 10.20.0.12
      - 10.20.0.254
    meta:
      configurable: false
      map_priority: 0
      notation: ip_ranges
      render_addr_mask: null
      render_type: null
      unmovable: true
      use_gateway: true
    name: fuelweb_admin
    vlan_start: null
settings:
  editable:
    external_dns:
      dns_list:
        description: List of upstream DNS servers, separated by comma
        label: DNS list
        regex:
          error: Invalid IP address list
          source: ^\*$|^(?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3}(?:\s*,\s*(?:\d|1?\d\d|2[0-4]\d|25[0-5])(?:\.(?:\d|1?\d\d|2[0-4]\d|25[0-5])){3})*$
        type: text
        value: 10.118.32.193
        weight: 10
      metadata:
        label: Host OS DNS Servers
        weight: 90
    external_ntp:
      metadata:
        label: Host OS NTP Servers
        weight: 100
      ntp_list:
        description: List of upstream NTP servers, separated by comma
        label: NTP server list
        regex:
          error: Invalid NTP server list
          source: ^\s*(?:(?:\w+(?:-+\w+)*\.)+[a-z]+|\d{1,3}(?:\.\d{1,3}){3})\s*(?:,\s*(?:(?:\w+(?:-+\w+)*\.)+[a-z]+|\d{1,3}(\.\d{1,3}){3})\s*)*$
        type: text
        value: 10.118.32.193
        weight: 10
    syslog:
      metadata:
        label: Syslog
        weight: 50
      syslog_port:
        description: Remote syslog port
        label: Port
        regex:
          error: Invalid syslog port
          source: ^([1-9][0-9]{0,3}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$
        type: text
        value: '514'
        weight: 20
      syslog_server:
        description: Remote syslog hostname
        label: Hostname
        type: text
        value: ''
        weight: 10
      syslog_transport:
        label: Syslog transport protocol
        type: radio
        value: tcp
        values:
        - data: udp
          description: ''
          label: UDP
        - data: tcp
          description: ''
          label: TCP
        weight: 30
